
#服务配置 server.port= 
#        server.servlet.context-path=
server:
  port: 80
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp